-- WYZ Design: merch orders + gift cards (schema of record)
-- Applied to project ccznkpcmpadgftqhwvdx on 2026-10-06 via the Supabase
-- Management API. This file versions that work (board task 42) so the schema
-- is reproducible. Idempotent: safe to re-run.
--
-- Access model: every table below has RLS enabled with NO policies, so only the
-- service role (server: checkout route + Stripe webhook) can read/write. The
-- browser never touches these tables directly.

-- ---------------------------------------------------------------------------
-- Merch orders
-- ---------------------------------------------------------------------------
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  stripe_session_id text unique,
  stripe_payment_intent text,
  email text,
  status text not null default 'paid',        -- pending | paid | fulfilled | cancelled | failed
  subtotal_cents integer not null default 0,
  shipping_cents integer not null default 0,
  total_cents integer not null default 0,
  currency text not null default 'usd',
  shipping_name text,
  shipping_address jsonb,
  printful_order_id text,
  printful_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.orders enable row level security;

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete cascade,
  printful_product_id bigint,          -- Printful sync_product_id
  printful_variant_id bigint not null, -- Printful sync_variant_id (exceeds int4)
  name text,
  variant_name text,
  quantity integer not null default 1,
  unit_price_cents integer not null default 0,
  image text,
  created_at timestamptz not null default now()
);
alter table public.order_items enable row level security;

create index if not exists orders_session_idx on public.orders(stripe_session_id);
create index if not exists order_items_order_idx on public.order_items(order_id);

-- ---------------------------------------------------------------------------
-- Gift cards (buy -> issue -> redeem)
-- ---------------------------------------------------------------------------
create table if not exists public.gift_cards (
  id bigint generated by default as identity primary key,
  stripe_session_id text,
  buyer_email text,
  recipient_email text,
  amount integer,                       -- face value in whole dollars
  balance_cents integer not null default 0,
  currency text not null default 'usd',
  code_hash text,                       -- sha256 of the normalized code (no plaintext)
  code_last4 text,                      -- support/display suffix
  status text not null default 'active',-- active | redeemed | void
  expires_at timestamptz,
  redeemed_at timestamptz,
  created_at timestamptz not null default now()
);
-- If the table pre-existed without these columns:
alter table public.gift_cards add column if not exists code_hash text;
alter table public.gift_cards add column if not exists code_last4 text;
alter table public.gift_cards add column if not exists balance_cents integer not null default 0;
alter table public.gift_cards add column if not exists currency text not null default 'usd';
alter table public.gift_cards add column if not exists recipient_email text;
alter table public.gift_cards add column if not exists redeemed_at timestamptz;
alter table public.gift_cards enable row level security;
create index if not exists gift_cards_hash_idx on public.gift_cards(code_hash);

create table if not exists public.gift_card_ledger (
  id uuid primary key default gen_random_uuid(),
  gift_card_id bigint not null references public.gift_cards(id) on delete cascade,
  delta_cents integer not null,
  reason text,                          -- reserved | redeemed | released | voided | refill
  ref text,                             -- reservation reference (checkout session)
  actor text,
  order_id uuid,
  created_at timestamptz not null default now()
);
alter table public.gift_card_ledger add column if not exists ref text;
alter table public.gift_card_ledger enable row level security;
create index if not exists gift_card_ledger_gc_idx on public.gift_card_ledger(gift_card_id);
create index if not exists gift_card_ledger_ref_idx on public.gift_card_ledger(ref);

-- ---------------------------------------------------------------------------
-- Atomic redemption (prevents two concurrent checkouts spending one balance)
-- All three are service-role only (no public/anon/authenticated grant).
-- ---------------------------------------------------------------------------
create or replace function public.reserve_gift_card(p_id bigint, p_max integer, p_ref text)
returns integer language plpgsql security definer set search_path = public as $$
declare v_balance integer; v_applied integer;
begin
  select balance_cents into v_balance from public.gift_cards
    where id = p_id and status = 'active' and (expires_at is null or expires_at > now())
    for update;
  if v_balance is null or v_balance <= 0 then return null; end if;
  v_applied := least(v_balance, greatest(p_max, 0));
  if v_applied <= 0 then return null; end if;
  update public.gift_cards
    set balance_cents = v_balance - v_applied,
        status = case when v_balance - v_applied <= 0 then 'redeemed' else 'active' end,
        redeemed_at = case when v_balance - v_applied <= 0 then now() else redeemed_at end
    where id = p_id;
  insert into public.gift_card_ledger (gift_card_id, delta_cents, reason, ref, actor)
    values (p_id, -v_applied, 'reserved', p_ref, 'checkout');
  return v_applied;
end; $$;

create or replace function public.commit_gift_card(p_id bigint, p_ref text)
returns void language sql security definer set search_path = public as $$
  update public.gift_card_ledger set reason = 'redeemed'
  where gift_card_id = p_id and ref = p_ref and reason = 'reserved';
$$;

create or replace function public.release_gift_card(p_id bigint, p_ref text)
returns void language plpgsql security definer set search_path = public as $$
declare v_applied integer;
begin
  select -delta_cents into v_applied from public.gift_card_ledger
    where gift_card_id = p_id and ref = p_ref and reason = 'reserved' limit 1;
  if v_applied is null then return; end if;
  update public.gift_cards set balance_cents = balance_cents + v_applied, status = 'active' where id = p_id;
  update public.gift_card_ledger set reason = 'released'
    where gift_card_id = p_id and ref = p_ref and reason = 'reserved';
  insert into public.gift_card_ledger (gift_card_id, delta_cents, reason, ref, actor)
    values (p_id, v_applied, 'released', p_ref, 'checkout-expired');
end; $$;

revoke all on function public.reserve_gift_card(bigint, integer, text) from public, anon, authenticated;
revoke all on function public.commit_gift_card(bigint, text) from public, anon, authenticated;
revoke all on function public.release_gift_card(bigint, text) from public, anon, authenticated;
